### PR TITLE
Feature/remove dist from src

### PR DESCRIPTION
**Pull request by dannyrb**
Taking a stab at this issue: https://github.com/cornerstonejs/cornerstone/issues/239

As we merge stuff fairly frequently into master, it might be nice to setup a better process for hotfixes and longer running feature/issues.

As part of this commit, I'll look into automating the `@next` release on merges, as there's no reason not to, so long as they don't break the build. Hopefully we can mimic this setup on our other repositories fairly easily.

Open to feedback.

TODO:

- [X] Verify readme still reflects usage
    - [X] Update CDN and `@next` information 
- [x] Update examples to use CDN
- [x] By hand verify that examples still work

### CODE REVIEW

**Comment by dannyrb** [comment]
Example of what was published to `@next`. Let me know if I should add/nix anything:

_root_
image

_root/dist_
image

**Comment by dannyrb** [comment]
https://semantic-release.gitbooks.io/semantic-release/content/#how-does-it-work

^ This. For `@next`. In a perfect world, eventually for `@latest`, but our process is a foot loose and fancy free at the moment.

**Comment by dannyrb** [comment]
@medihack && @swederik this is ready to `merge` unless you have thoughts/suggestions. `semantic-release` will be added separately after I get a 👍 from @swederik.

**Comment by dannyrb** [comment]
@swederik defaults to local unminified source from dist, if it's not there, it will attempt to grab `@latest` from the CDN

**Comment by swederik** [comment]
Hooray :-D This should make contributions easier. Much less 'can you please rebase this?'

**Pull request merged**
