### PR TITLE
Check whether the horizontal axis is the x or y axis (depends on rotation)

### PR DESCRIPTION
**Pull request by adreyfus**
Before correction, if we rotated the image then we flip it horizontally, it flipped vertically.

If we then tried to use the zoom tool, it was buggy because the algorithm of zoom assumes that the image has been flipped horizontally.

### CODE REVIEW

**Comment by adreyfus** [comment]
For any questions or suggestions, you can contact me here or by email.

**Comment by swederik** [comment]
Hi Aloïs,

I'm not sure I see the buggy behaviour. Could you explain what it is?

I added the Zoom tool to the flip / rotate example here (zoom is on left-click): https://rawgit.com/chafey/cornerstone/fliprotatebug/example/flip%26rotation/index.html

Thanks!

**Comment by adreyfus** [comment]
Hi,

I don't remember what was the side effect with the zoom tool, but the bug is the first part : 
Before correction, if we rotated the image then we flip it horizontally, it flipped vertically.

**Comment by swederik** [comment]
Hi Aloïs,

That is intended behaviour. Flipping vertically will apply the flip along the image's vertical direction, even if it has been rotated.

**Pull request closed without merging**
