### PR TITLE
Correct float access to lut array (#302)

### PR DESCRIPTION
**Pull request by pierreldff**
Computation of modalityLut values with float rescale slope/intercept could lead to float values.
To access to the lut array we need to get integer values other wise we will get no values

### CODE REVIEW

**Comment by swederik** [comment]
This makes sense. I also don't have issues running the tests. I don't know why Travis is having issues, let me restart the build to see if that changes anything.

**Comment by dannyrb** [comment]
Is this related to: https://github.com/cornerstonejs/cornerstone/issues/302#issuecomment-419851291 ?

I'm unsure of how to action this item. Any guidance would be appreciated.

**Comment by pierreldff** [comment]
Ok so i had a flag to check if slope intercept cannot be cast as integer.
We pass the flag if we compute nonlinearVOILUT

**Pull request merged**
