### PR TITLE
compute VOI

### PR DESCRIPTION
**Pull request by adreyfus**
The default behavior does not change (because `viewport.computeVoi === undefined`).

To activate the VOI computing for a viewport, just create a `viewport.computeVoi = {};`.

If the pull request is accepted, I will publish the code in cornerstoneWADOImageLoader to store voiPresetTab into image.data.storedValues.

### CODE REVIEW

**Comment by adreyfus** [comment]
For any questions or suggestions, you can contact me here or by email.

**Comment by adreyfus** [comment]
if viewport.computeVoi === undefined, getViewport() no longer adds the undefined attribute computeVoi

=> reset_test: success

**Comment by swederik** [comment]
@Zaid-Safadi is going to reconcile this with the changes in https://github.com/cornerstonejs/cornerstone/pull/211 on the voi-lut branch

**Comment by Zaid-Safadi** [comment]
@adreyfus , can you help me validate my understanding for this change?

- You are adding a new property "computeVoi" to the viewport object with the following properties:
1. forceAutoVoi
2. type
3. voiPresetIndex

- Then adding a new method which name is also "computeVoi" to calculdate the WW/WC based on the properties in this "computeVoi" object.

- There is also an assumption that the user should know to add the "image.data.storedValues.voiPresetTab" to the "image" object for this method to work only if (type != "FIXED" and forceAutoVoi == false).

If my above understanding is correct, then:
1. Would it make sense to add these new properties to the viewport.voi object and remove the new property "computeVoid"? 
2. I have a concern that there is a hidden assumptions and knowledge that is not obvious without reading documentation to use this method. 
This might be improved if these 3 new fields are part of the standard viewport.voi object and documented.
Also, I am think the "storedValues.voiPresetTab" should be grouped with the new fields since they are related.

Please let me know your thoughts.

**Comment by adreyfus** [comment]
Hi Zaid,

I think you are right, it makes sense to group them to the viewport.voi object. The idea behing the new property "computeVoi" was to not perturb the default behavior.

**Comment by Zaid-Safadi** [comment]
@adreyfus 
 
I’d like to get your feedback on the changes I am proposing to your PR and see if the new way accommodate your use-cases.
-	No need for the “computeVoi” property on the viewport (removed)
-	 Added a new property voiPresets: [] //{ww, wc, voiLUT} to the viewport.voi object
This now will be the same as “image.data.storedValues.voiPresetTab” that is created in the WADOImageLoader
-	The “forceAutoVoi" and “voiPresetIndex” are now passed as parameters to the computeVoi
-	The “computeVoi.type” is not needed anymore. The method logic will replace it.
-	The computeVoi method is now exported and can be called externally

The computeVoi method logic has changed:
-	Instead of setting computeVoi.type = ‘Fixed’ just don’t call this method
-	Instead of setting forceAutoVoi = true, pass the parameter forceAuto to the method parameters.
-	Instead of checking if an external module (WADOLoader) is setting storedValues.voiPresetTab on the image.data, just set this standard voi.voiPresets on the viewport.voi and pass the selected preset index to the method parameter (optional)

While I haven’t tested this code yet or added test cases, I committed the changes to the [**"voi-lut"**](https://github.com/cornerstonejs/cornerstone/commit/3054d136663fd903cce1fc58029b52560282ea87) branch and I like to see if you have any comments before doing so. I feel these changes will make it simpler to use this functionality and add the features from [PR-211](https://github.com/cornerstonejs/cornerstone/pull/211).

**Comment by adreyfus** [comment]
Hi @Zaid-Safadi, thank you for your hard work. Your changes seem very good and if by testing I realize that something is missing, I will propose a PR after yours is merged.

**Comment by Zaid-Safadi** [comment]
I have completed all the changes to this PR in the [**"voi-lut"**](https://github.com/cornerstonejs/cornerstone/commit/676243c15952afddd8084b54e81ee33e6dfd11f0) branch and updated the HTML example "modalityANDVIOLut" to show the new features.

@adreyfus please feel free to check the example, it now has the following features:
1- Reset VOI LUT (forceAuto)
2- Select a VOI from defined presets (W/L values or and VOI LUT function)

This is now ready to be merged to master

**Pull request merged**
