### PR TITLE
Rescale automatically when resizing. Fixes #216

### LINKED ISSUE #216: Retain scale when resizing
When calling `resize` on an `enabledElement` (maybe because the layout changed or the browser window was resized) there currently seems to be no way to retain the scale of the image. When calling `resize` with `fitViewportToWindow === true` the image is resized to fit the viewport (as expected). Calling it with `fitViewportToWindow === false` then the visible part of the image may be cut off (when the resized canvas is smaller). It would be nice if there is a way to show the image in the same way it was presented before the `resize`, just larger or smaller.

### PR DESCRIPTION
**Pull request by medihack**
Additional notes on the issue #216

### CODE REVIEW

**Comment by dannyrb** [comment]
Thanks for the PR, @medihack! On my list to review today :+1:

**Comment by medihack** [comment]
I am still thinking about adding a new parameter `resize(rescaleStrategy)`. That way it will behave completely like before when calling just `resize()` without any rescaling. Optional strategies then would be `NO_RESCALE` (default when no strategy is provided), `FIT_TO_WINDOW` (same as `true` parameter now), `FIXED_RESCALE` ([square root of the relative change](https://github.com/cornerstonejs/cornerstone/pull/227/files#diff-262c66f7ba686899b87c19f0c6b6007cR102)) and `SMART_RESCALE` (the algorithm I implemented as a mix of FIT_TO_WINDOW and FIXED_RESCALE). What do you think? On the other side in nearly all cases the algorithm in the existing pull request is IMHO the way to go.

**Comment by dannyrb** [comment]
I like your refactor. Much cleaner, @medihack :+1:
I think this is good for a merge.

If we're going to create new strategies, then it might be worth creating a way to set a default as a config property when initializing Cornerstone? That way you can set your default behavior, update your default behavior later, and override it on individual resize calls.

All great stuff for a separate PR? No need to over-complicate this one if it's ready to ship, unless you think it would set us up for a breaking change.

**Comment by medihack** [comment]
Ok, then let's merge. I think users will directly benefit from this when rescaling is the default. I will come up with those strategies in another PR somewhen later (or when other users demand it).

**Comment by dannyrb** [comment]
@swederik can you pull the lever on this? Want to make sure I'm not stepping on your toes for this project.

**Comment by swederik** [comment]
Looks good to me!

**Pull request merged**
