### PR TITLE
TypeScript Definition

### PR DESCRIPTION
**Pull request by iamssen**
Update to support TypeScript definition.

Fixes related to Travis CI or Yarn are also included.

# Added
- TypeScript Definition

# Fixed
- Remove package-lock.json file for prevent travis-ci error
- Update yarn.lock file dependencies `upath@1.2.0`

### CODE REVIEW

**Comment by dannyrb** [comment]
@iamssen, how did you generate the definitions? I'm hesitant to add them unless we have a good process for maintaining them.

**Comment by iamssen** [comment]
@dannyrb This typescript definition was not created automatically using jsdoc comments.

I wrote this typescript definition with reference to the API documentation and source codes.

If this typescript definition behaves abnormally due to API changes, I or some other typescript user will update this definition.

**Comment by dannyrb** [comment]
@iamssen, hmm.. Okay.
I can probably merge this, but I'll want to add a note to our readme that they're not actively maintained and rely on volunteers to correct any issues.

Can you undo the `yarn.lock` and adding `package-lock.json` to `.gitignore`? All `cornerstonejs` libraries use `npm`, not `yarn`.

**Comment by iamssen** [comment]
@dannyrb I restored `package-lock.json` file and `yarn.lock` file. 🙂

However, there is a problem with the restored `yarn.lock` that will cause errors in travis ci.

<https://travis-ci.org/cornerstonejs/cornerstone/jobs/586327266#L228>

If cornerstone uses `npm` instead of `yarn`, delete the `yarn.lock` file and remove the `cache` entry from the `travis.yml` file and the error in travis ci will disappear.

<https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn>

**Comment by dannyrb** [comment]
I'll follow your advice tomorrow morning ^_^
Thanks for the contribution and support, @iamssen!

**Comment by dannyrb** [comment]
👀 are still on this

**Comment by iamssen** [comment]
??? I knew you wanted me not to modify configuration files like travis or lock files. 😅

**Comment by macrusso** [comment]
any update on this?

**Comment by mariolugo** [comment]
any updates on this?

**Comment by deminoth** [comment]
https://www.npmjs.com/package/@types/cornerstone-core was just published.

**Pull request closed without merging**
