### PR TITLE
Export event constants as default. Fixes #235

### LINKED ISSUE #235: Export event constants as default and EventTarget as named export
It would be cleaner to export the constants as default (like CornerstoneTools does) and the EventTarget as a named export. In this context, I would also export the constants globally (for the cornerstone object), as in [CornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools/pull/334). I create a PR.

### PR DESCRIPTION
**Pull request by medihack**
Not sure if you like the name `eventProxy`, just thought it would be a more suitable name and also to distinguish it from `EVENTS`.

### CODE REVIEW

**Comment by dannyrb** [comment]
LGTM 👍 
Assigned @swederik for a quick doublecheck

**Comment by swederik** [comment]
Yeah seems fine to me. I can't merge due to conflicts though :-(

(we should really investigate keeping built files out of the repo)

**Comment by medihack** [comment]
@swederik I updated the PR with the rebuilt and merged in dist files. And I'm all for not to include the dist files in GitHub (it's a bit like storing binary files at GitHub). We could just add those files to GitHub releases (maybe this can be automated by some NPM script in package.json, but not sure).

**Comment by swederik** [comment]
Thanks!

Yeah I am open to suggestions. The problem I think is that people using NPM may depend on dist/whatever being present.

**Comment by swederik** [comment]
Whoops, looks like this broke 

https://github.com/cornerstonejs/cornerstone/blob/961a4ffd7a4045c1395e43d2e6538a22d9bc33be/example/eventhandling/index.html

since it still relies on cornerstone.events. What about cornerstoneTools? Isn't that also relying on cornerstone.events? Is that also broken by the switch to 'eventProxy'?

**Pull request merged**
