### PR TITLE
Move all event names to events.js. Fixes #231

### LINKED ISSUE #231: List all events in events.js
It would be nice to have all Cornerstone events (and used throughout the library) as constants in `events.js` ([like CornerstoneTools does](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/events.js)).

### PR DESCRIPTION
**Pull request by medihack**

### CODE REVIEW

**Comment by dannyrb** [comment]
@swederik, this has my 👍 
Cornerstone-core is more your baby, though. Leaving it to you to pull the `merge` lever.

**Comment by swederik** [comment]
This looks good to me as well, but there are some conflicts so I guess you'll need to rebase it.

**Comment by medihack** [comment]
Ok, ready to go.

**Comment by swederik** [comment]
Thanks!

**Pull request merged**
